### PR TITLE
Typescript conversion

### PR DESCRIPTION
**Pull request by RaffaelSchaefer**
# Typescript conversion
The codebase can now be complied with typescript.
Its not perfect but its works, I will improve on it in the future.

### CODE REVIEW

**Comment by Checker8763** [comment]
I will push some improvments.
Then we can discuss again.

**Comment by Checker8763** [comment]
I think it is ready to merge pls respond.

**Comment by RaffaelSchaefer** [comment]
# LEEEEEEEEEEEEEEEETS GOOOOOOOOOOOOOOOOOOOOOOO
Lets merge Dapull request to Damain

image

**Comment by RaffaelSchaefer** [comment]
Yee

**Pull request merged**
